# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  docker:
    - image: cypress/base:10
      environment:
        TERM: xterm # This enables colors in the output
version: 2.1
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          keys:
            - v1-dependencies
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ~/.cache
          key: v1-dependencies
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .next
  unit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn test:unit
  e2e:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - attach_workspace:
          at: .
      - run: yarn test:e2e
workflows:
  build_and_test:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - e2e:
          requires:
            - build
      - unit:
          requires:
            - build
